[General]
appAutoLocking=false
app_install_time=1775941923
app_launched_count=1
autoLockDuration=30
firstrun_tray=false
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\x4\xe7\0\0\x2\x9d\0\0\0\0\0\0\0\0\0\0\x2l\0\0\x2\x9d\0\0\0\0\x2\0\0\0\x5\0\0\0\0\0\0\0\0\0\0\0\x4\xe7\0\0\x2\x9d)
lockscreen=false
notificationCombo=1
notificationTimeOut=9000
widgetStyle=Fusion
windowTheme=light

[permissions]
Notifications=true
